version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: patent-postgres
    environment:
      POSTGRES_DB: patents
      POSTGRES_USER: patent_user
      POSTGRES_PASSWORD: patent_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U patent_user -d patents"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - patent-network

  neo4j:
    image: neo4j:5.15-community
    container_name: patent-neo4j
    environment:
      NEO4J_AUTH: neo4j/patent_password
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p patent_password 'RETURN 1'"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - patent-network

volumes:
  postgres_data:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local

networks:
  patent-network:
    driver: bridge
